[17-Apr-2019 01:47:46 UTC] Uncaught exception: 'ErrorException' with message 'array_keys() expects parameter 1 to be array, null given'
Stack trace: #0 [internal function]: JanKlod\Exception\ErrorHandler::errorHandler(2, 'array_keys() ex...', 'D:\\laragon\\www\\...', 157, Array)
#1 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(157): array_keys(NULL)
#2 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(171): JanKlod\Validation\Validate->getTranslate('username is req...')
#3 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(67): JanKlod\Validation\Validate->addError('username is req...')
#4 D:\laragon\www\Framework\app\controllers\TaskController.php(170): JanKlod\Validation\Validate->check(Array, Array)
#5 D:\laragon\www\Framework\app\controllers\TaskController.php(70): app\controllers\TaskController->isValidData()
#6 [internal function]: app\controllers\TaskController->add()
#7 D:\laragon\www\Framework\src\Engine\Routing\Dispatcher.php(102): call_user_func_array(Array, Array)
#8 D:\laragon\www\Framework\src\Engine\Foundation\Application.php(74): JanKlod\Routing\Dispatcher->run(Object(JanKlod\Container\DI\DIC))
#9 D:\laragon\www\Framework\public\index.php(36): JanKlod\Foundation\Application->run()
#10 {main}
Thrown in 'D:\laragon\www\Framework\src\Engine\Validation\Validate.php' on line 157
[17-Apr-2019 01:48:59 UTC] Uncaught exception: 'ErrorException' with message 'array_keys() expects parameter 1 to be array, null given'
Stack trace: #0 [internal function]: JanKlod\Exception\ErrorHandler::errorHandler(2, 'array_keys() ex...', 'D:\\laragon\\www\\...', 157, Array)
#1 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(157): array_keys(NULL)
#2 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(171): JanKlod\Validation\Validate->getTranslate('username is req...')
#3 D:\laragon\www\Framework\src\Engine\Validation\Validate.php(67): JanKlod\Validation\Validate->addError('username is req...')
#4 D:\laragon\www\Framework\app\controllers\TaskController.php(170): JanKlod\Validation\Validate->check(Array, Array)
#5 D:\laragon\www\Framework\app\controllers\TaskController.php(70): app\controllers\TaskController->isValidData()
#6 [internal function]: app\controllers\TaskController->add()
#7 D:\laragon\www\Framework\src\Engine\Routing\Dispatcher.php(102): call_user_func_array(Array, Array)
#8 D:\laragon\www\Framework\src\Engine\Foundation\Application.php(74): JanKlod\Routing\Dispatcher->run(Object(JanKlod\Container\DI\DIC))
#9 D:\laragon\www\Framework\public\index.php(36): JanKlod\Foundation\Application->run()
#10 {main}
Thrown in 'D:\laragon\www\Framework\src\Engine\Validation\Validate.php' on line 157
